from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import io
from datetime import date

def generate_dmr_report(farm_name, country, area_ha, geometry, ndvi):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 18)
    c.drawString(1*inch, height - 1*inch, "EcoPlotAI dMRV Verification Report")

    c.setFont("Helvetica", 10)
    c.drawString(1*inch, height - 1.3*inch, f"Aligned with Country NDCs & Article 6 Carbon Markets")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1*inch, height - 2*inch, "1. Farm Details")
    c.setFont("Helvetica", 10)
    c.drawString(1*inch, height - 2.3*inch, f"Farm Name: {farm_name}")
    c.drawString(1*inch, height - 2.6*inch, f"Country: {country}")
    c.drawString(1*inch, height - 2.9*inch, f"Report Date: {date.today().strftime('%B %d, %Y')}")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1*inch, height - 3.4*inch, "2. Verified Geospatial Data")
    c.setFont("Helvetica", 10)
    c.drawString(1*inch, height - 3.7*inch, f"Verified Area: {area_ha:.2f} Hectares")
    c.drawString(1*inch, height - 4.0*inch, f"Boundary Points: {len(geometry.exterior.coords)}")
    c.drawString(1*inch, height - 4.3*inch, f"Vegetation Index NDVI: {ndvi}")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1*inch, height - 4.8*inch, "3. dMRV Compliance Statement")
    c.setFont("Helvetica", 9)
    text = c.beginText(1*inch, height - 5.1*inch)
    text.textLines(f"""This report provides digital, verifiable data for Measurement, Reporting,
and Verification of farm-level land use. Data is suitable for submission to
Country NDC tracking systems and Article 6.2/6.4 carbon market registries.

Methodology: Satellite + Field Boundary Verification
Accuracy: ±5%
Generated by: EcoPlotAI Platform""")
    c.drawText(text)

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1*inch, 0.75*inch, "EcoPlotAI - Building MRV Infrastructure for Africa's Green Economy")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer
